'use client';

import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import Navbar from "./navbar/page";
import { appWithTranslation } from 'next-i18next';
import { useTranslation } from 'next-i18next';
import { LanguageProvider } from './context/LanguageContext';

function RootLayout({ children }) {
  const { t, i18n } = useTranslation();
  const dir = i18n.language === 'ar' ? 'rtl' : 'ltr';

  return (
    <AuthProvider>
      <LanguageProvider>
      <html lang={i18n.language} dir={dir}>
      <head>
        <title>{t('page.home.title')}</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      {/* <body className="bg-gray-100 grid grid-rows-layout min-h-screen"> 
        <Navbar />
        <main className="row-start-3 p-4"> 
          {children}
        </main>
      </body> */}
      <body className="bg-gray-100 grid grid-rows-[auto_1fr]"> {/* Define a grid layout */}
  <div className="row-start-2 col-span-5">
    <Navbar />
  </div>
  <main className="row-start-3 col-span-5 p-4"> 
    {children}
  </main>
</body>


      
{/* <div className="grid grid-cols-5 grid-rows-5 gap-4">
    <div className="col-span-5">1</div>
    <div className="col-span-5 row-span-4 row-start-2">3</div>
</div> */}
    
    </html>

      </LanguageProvider>
    </AuthProvider>
  );
}

export default appWithTranslation(RootLayout);
