'use client';

import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import Navbar from "./navbar/page";
import { appWithTranslation } from 'next-i18next';
import { useTranslation } from 'next-i18next';
import { LanguageProvider } from './context/LanguageContext';

function RootLayout({ children }) {
  const { t, i18n } = useTranslation();
  const dir = i18n.language === 'ar' ? 'rtl' : 'ltr';

  return (
    <AuthProvider>
      <LanguageProvider>
        <html lang={i18n.language} dir={dir}>
          <head>
            <title>{t('page.home.title')}</title>
            <meta name="description" content="Generated by create next app" />
          </head>
          <body>
            <Navbar />
            {children}
          </body>
        </html>
      </LanguageProvider>
    </AuthProvider>
  );
}

export default appWithTranslation(RootLayout);
