'use client';

import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import Navbar from "./navbar/page";
import { appWithTranslation } from 'next-i18next';
import { useTranslation } from 'next-i18next';
import { LanguageProvider } from './context/LanguageContext';
import './i18n' 
function RootLayout({ children }) {
  const { t, i18n } = useTranslation();
  const dir = i18n.language === 'ar' ? 'rtl' : 'ltr';

  return (
    <AuthProvider>
      <LanguageProvider>
      <html lang={i18n.language} dir={dir}>
      <head>
        <title>{t('page.home.title')}</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className="bg-gray-100 grid grid-rows-[auto_1fr]"> 
  <div className="row-start-2 col-span-5">
    <Navbar />
  </div>
  <main className="row-start-3 col-span-5 p-4"> 
    {children}
  </main>
</body>


    
    </html>

      </LanguageProvider>
    </AuthProvider>
  );
}

export default appWithTranslation(RootLayout);
